version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./Act1:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Act1Apli
    ports:
      - "3307:3307"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge